In [8]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as seab
import statsmodels as statmods
from numpy.random import randn

In [2]:
for i in range(7):
    data = {i : np.random.randn()}

In [3]:
data

{6: 0.22857091132880877}

In [13]:
data_2 = {x : randn() for x in range(7)}

In [14]:
print(data_2)

{0: -0.8948815061530283, 1: 0.4825164022715219, 2: 0.6443746902487422, 3: -0.2701978975624823, 4: 0.6238264361889262, 5: 0.7691976576794292, 6: 1.893485045967809}


In [10]:
data_2

{6: -0.8635205610517901}

In [20]:
data_3 = np.random.randn(2,3)
print(data_3)
print(data_3 * 10)

[[-1.29635564 -0.23186194 -1.77613984]
 [-0.60338877 -2.43654858  0.44024614]]
[[-12.96355644  -2.31861935 -17.76139841]
 [ -6.03388767 -24.3654858    4.40246141]]


In [21]:
#kształt tablicy wyświetlamy dzięki shape
data_3.shape

(2, 3)

In [22]:
#typ danych wyświetlamy dzięki dtype
data_3.dtype

dtype('float64')

In [3]:
#tworzenie tablicy ndarray 
import numpy as np

data1 = [4,5,6,7,9]
arr1 = np.array(data1)
arr1

array([4, 5, 6, 7, 9])

In [4]:
data2 = [[2,3,4,5],[4,5,6,7]]
arr2 = np.array(data2)
arr2

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [5]:
#data2 ma dwa wymiary można to sprawdzić dzięki ndim i shape
arr2.ndim

2

In [6]:
arr2.shape

(2, 4)

In [7]:
#sprawdzenie typu tablicy 
arr1.dtype

dtype('int32')

In [8]:
arr2.dtype

dtype('int32')

In [9]:
#funkcje zeros i ones 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((2, 3, 2))

array([[[6.e-322, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]],

       [[0.e+000, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]]])

In [13]:
#funkcja arange
np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
#funkcja dtype jest obiektem zawierającym informacje na temat typu danych. 
#Dzieki niemu Python wie jak interpretować określony obszar pamięci 
arr3 = np.array([2,3,4,5,6], dtype = np.float64)
arr3.dtype

dtype('float64')

In [16]:
#metoda astype umożliwia jawną konwersjęjednego typu danych na inny 
arr4 = np.array([2,5,6,7,8])
arr4.dtype

dtype('int32')

In [17]:
float_arr4 = arr4.astype(np.float64)
float_arr4.dtype

dtype('float64')

In [18]:
#konwertowanie stringa na floata
numeric_string = np.array(['1.23', '-6.7', '8.99'], dtype = np.string_)
numeric_string.astype(float)

array([ 1.23, -6.7 ,  8.99])